In [ ]:
import cv2
import numpy as np
import keras
from keras.models import Model, Sequential
from keras.layers import *
from keras.activations import *
from keras.optimizers import Adam,RMSprop,SGD
x = np.load("x.npy")
y = np.load("y.npy")
shuffe_index = np.random.permutation(x.shape[0])
N = x.shape[0]
K = int(0.8*N)#number of train samples
index = np.random.permutation(N)
x_train = x[index[0:K]]
y_train = y[index[0:K]]
x_test = x[index[K:]]
y_test = y[index[K:]]
print(N, K, N - K)
print(x.shape)

In [2]:
print(x_train)



[[[[ 55  82  78]
   [ 53  80  76]
   [ 51  78  74]
   ...
   [ 33  55  50]
   [ 43  65  60]
   [ 46  68  63]]

  [[ 54  81  77]
   [ 53  80  76]
   [ 51  78  74]
   ...
   [ 33  55  50]
   [ 42  64  59]
   [ 45  67  62]]

  [[ 53  80  76]
   [ 53  80  76]
   [ 51  78  74]
   ...
   [ 34  56  51]
   [ 44  67  62]
   [ 46  69  64]]

  ...

  [[ 38 115 101]
   [ 39 116 102]
   [ 41 117 105]
   ...
   [ 84 128 121]
   [ 94 136 129]
   [ 98 139 132]]

  [[ 40 114 102]
   [ 42 116 104]
   [ 47 119 107]
   ...
   [ 85 127 120]
   [ 96 134 128]
   [100 136 130]]

  [[ 42 114 102]
   [ 43 115 103]
   [ 50 119 108]
   ...
   [ 86 127 120]
   [ 97 133 127]
   [102 136 130]]]


 [[[ 80  90  97]
   [ 77  87  94]
   [ 74  83  87]
   ...
   [ 81 124 121]
   [ 85 127 126]
   [ 84 128 127]]

  [[ 80  90  97]
   [ 79  89  96]
   [ 77  86  90]
   ...
   [ 82 122 120]
   [ 84 126 125]
   [ 83 127 126]]

  [[ 81  90  94]
   [ 81  90  94]
   [ 77  88  92]
   ...
   [ 81 120 118]
   [ 84 124 123]
   [ 84 126

In [3]:
model = Sequential()

model.add(Conv2D(8, kernel_size=(5, 5), strides= (2, 2), padding='same',input_shape=( 64, 64, 3,)))
model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(16, kernel_size=(3, 3), strides= (1, 1), padding='same'))
model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, kernel_size=(3, 3), strides= (1, 1), padding='same'))
model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dropout(0.3))
model.add(Dense(2))
model.add(Activation('sigmoid'))
optimizer = Adam(lr=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)
model.summary()


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 32, 32, 8)         608       
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 32, 32, 8)         0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 8)         0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 16, 16, 16)        1168      
_________________________________________________________________
leaky_re_lu_2 (LeakyReLU)    (None, 16, 16, 16)        0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 8, 8, 16)          0         
_________________________

In [4]:
print (x_test.shape[0], x_train.shape[0])

61 243


In [5]:
def generator(x, y, batch_size):
    samples = x.shape[0]
    steps = samples/batch_size
    counter =0
    while True:
        batch_x = np.array(x[batch_size*counter: batch_size*(counter+1)]).astype(np.float32)
        batch_x = batch_x/255.0
        batch_y = np.array(y[batch_size*counter: batch_size*(counter+1)]).astype(np.float32)
        counter+=1
        yield batch_x, batch_y
        if counter >= steps:
            counter = 0
# batch_size = 128
batch_size = 32
epochs=50
from keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint("models/sign.h5", monitor='val_loss', verbose=1, save_best_only=True, mode='min')
history= model.fit_generator(generator(x_train, y_train, batch_size), epochs=epochs, steps_per_epoch = x_train.shape[0]/batch_size, 
                             validation_data=generator(x_test, y_test, batch_size), validation_steps = x_test.shape[0]/batch_size, callbacks=[checkpoint])


Epoch 1/50
8/7 [===============================] - 0s 48ms/step - loss: 0.4926 - val_loss: 0.3511

Epoch 00001: val_loss improved from inf to 0.35113, saving model to models/sign.h5
Epoch 2/50
8/7 [===============================] - 0s 14ms/step - loss: 0.3268 - val_loss: 0.2611

Epoch 00002: val_loss improved from 0.35113 to 0.26112, saving model to models/sign.h5
Epoch 3/50
8/7 [===============================] - 0s 12ms/step - loss: 0.2668 - val_loss: 0.2434

Epoch 00003: val_loss improved from 0.26112 to 0.24335, saving model to models/sign.h5
Epoch 4/50
8/7 [===============================] - 0s 12ms/step - loss: 0.2669 - val_loss: 0.1695

Epoch 00004: val_loss improved from 0.24335 to 0.16945, saving model to models/sign.h5
Epoch 5/50
8/7 [===============================] - 0s 11ms/step - loss: 0.2338 - val_loss: 0.1265

Epoch 00005: val_loss improved from 0.16945 to 0.12653, saving model to models/sign.h5
Epoch 6/50
8/7 [===============================] - 0s 12ms/step - loss: 0

8/7 [===============================] - 0s 12ms/step - loss: 6.5204e-04 - val_loss: 0.0031

Epoch 00050: val_loss did not improve from 0.00085


In [6]:
import cv2
import numpy as np
from keras.models import load_model
import time
model = load_model("models/sign.h5")


In [ ]:
t = time.time()
predict = model.predict(x_test/255.0)
print(time.time()-t)
for i in range(x_test.shape[0]):
    img = x_test[i]
    img = cv2.resize(img, (128, 128))
    print(predict[i])
    if predict[i,1]>0.5:
        if predict[i,0]<0.9:
            cv2.rectangle(img, (0,0), (30, 30), (0, 0, 255), -1)
        else:
            cv2.rectangle(img, (98, 0), (128, 30), (0, 0, 255), -1)
    cv2.imshow("img", img)
    k =cv2.waitKey(0)
    if k == ord('q'):
        break
cv2.destroyAllWindows()

0.07115602493286133
[0.99999845 1.        ]
[0.00312188 0.9999993 ]
[0.99979424 0.9999852 ]
[0.9999997 1.       ]
[0.99998474 0.9999999 ]
[1.3104081e-04 1.0000000e+00]
[0.99993443 0.9999999 ]
[3.8522482e-04 1.0000000e+00]
[0.0012387 1.       ]
[1.7467141e-04 1.0000000e+00]
[0.10398987 0.9999988 ]
[0.99977183 0.9999964 ]
[0.9999775 0.9999989]
[0.001398   0.99998736]
[6.5863132e-06 1.0000000e+00]
[0.9999994 1.       ]
[0.00150341 0.99999845]
[1.218915e-05 9.999999e-01]
[0.9999976 0.9999998]
[0.9988513 0.9999933]
[0.9999983  0.99999994]


In [7]:
print (x_test.shape)

(61, 64, 64, 3)


In [45]:
def classify():
    img = cv2.imread('test/cropleft1.png')

    img = cv2.resize(img, (64, 64))
#     print img.shape
#     with graph.as_default():
#         set_session(sess)
#         side, conf = model.predict(img)
    side, conf = model.predict(np.array([img])/255.0)[0]
    

    print side, conf


In [46]:
classify()

5.090714e-06 1.0


In [3]:
import timeit
from datetime import timedelta

# sess = tf.Session()

# graph = tf.get_default_graph()

# set_session(sess)
# my_model = load_model('models/sign_fix.h5')
# my_model = load_model('models/sign_fix.h5')

sign_cascade = cv2.CascadeClassifier('models/cascade2.xml')

crop = np.zeros((64, 64), np.uint8)

def FindSign(img):
    signs = sign_cascade.detectMultiScale(img,
                                          scaleFactor=1.03,
                                          minNeighbors=2,
                                          minSize=(19, 19),
                                          maxSize=(60, 60),
                                          flags=0)
    return signs


def Cascade_sign(img_):
    global crop, sess, graph
    t = 2
    side = None
    img = img_[0:100, ...].copy()
    img2 = img_[0:100, ...].copy()
    signs = FindSign(img2)
    position = None
    for (x, y, w, h) in signs:
        if x > 5 and y > 5 and x + w < 475 and y + h < 95 and 1.0 * h / w > 0.85 and 1.0 * h / w < 1.3:
            print(w, h)
            position = [x, y, w, h]
            crop = img[y - t:y + h + t, x - t:x + w + t, :]
            crop = cv2.resize(crop, (64, 64))
            start = timeit.default_timer()
#             with graph.as_default():
#                 set_session(sess)
#                 _side, confident = my_model.predict(np.array([crop]) /
#                                                     255.0)[0]
#                 print('toi dang o day')
#                 print('confident = ', confident)
            _side, confident = model.predict(np.array([crop]) /
                                                    255.0)[0]
            stop = timeit.default_timer()
            print ('Thoi gian chay model la ', stop - start)
            #_side, confident = sign_model.predict(np.array([crop])/255.0)[0]
            # _side = 0
            # confident = 0.9
            if _side < 0.5:
                _side = 0
            else:
                _side = 1
            if confident > 0.5:
                side = _side
            # cv2.rectangle(img,(x-t,y-t),(x+w+t,y+h+t),(0,255,0),2)
            # font = cv2.FONT_HERSHEY_SIMPLEX
            # cv2.putText(img,str(confident),(x-10,y-10), font, 0.5, (255,255,255), 1, cv2.LINE_AA)
            # #cv2.imshow('crop', crop)
    return crop, side, img, position

# time.sleep(5)


def testImage():
    img = cv2.imread('test/left1.png')

    crop1, side, img2, pos = Cascade_sign(img)
    #cv2.imshow('crop', crop)
    #cv2.imshow('sign', img2)
    #cv2.imshow('image', img)
    print ('side= ', side)
    print ('pos= ', pos)
    #getMask(img)

    cv2.waitKey(0)


In [ ]:
testImage()

In [44]:
img = cv2.imread('test/left1.png')

signs = FindSign(img)

for (x, y, w, h) in signs:
        if x > 5 and y > 5 and x + w < 475 and y + h < 95 and 1.0 * h / w > 0.85 and 1.0 * h / w < 1.3:
            print(w, h)

(26, 26)


In [ ]:
cl